name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build Backend
      run: ./mvnw clean package
      working-directory: ./backend/api_service

  test_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Run Backend Tests
      run: ./mvnw test
      working-directory: ./backend/api_service

  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend/central-web

    - name: Build Frontend
      run: npm run build
      working-directory: ./frontend/central-web

  test_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend/central-web

    - name: Run Frontend Tests
      run: npm run test -- --no-watch --browsers=ChromeHeadless

  package_backend:
    runs-on: ubuntu-latest
    needs: build_backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Package Backend
      run: ./mvnw clean package
      working-directory: ./backend/api_service

    - name: Save Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api.jar
        path: ./backend/api_service/target/api.jar
